### ISSUE TITLE
Darker and Graylint configuration dump with `-vv` shows wrong section `[tool.darkgraylib]`

### ISSUE THREAD

**Issue by akaihola** [akaihola/darkgraylib#56]
When running Darker or Graylint with the `-vv` verbosity level, the configuration dump looks something like this:
```toml

# Effective configuration:

[tool.darkgraylib]
src = [
    "subsubdir",
]
revision = "a994113583799adf80386ee5519802661a9b2c79...72c491b312e61c9a38d0d66fce1b05c15bc46e60"
log-level = "DEBUG"
workers = 1
diff = true
stdout = false
check = false
flynt = false
isort = false
lint = [
]


# Configuration options which differ from defaults:

[tool.darkgraylib]
src = [
    "subsubdir",
]
revision = "a994113583799adf80386ee5519802661a9b2c79...72c491b312e61c9a38d0d66fce1b05c15bc46e60"
log-level = "DEBUG"
diff = true
```

The section name should of course be `[tool.darker]` or `[tool.graylint]` instead.
